### ISSUE TITLE
postParentObject

### ISSUE THREAD

**Issue by cesagonchu** [XoopsModules25x/newbb#77] opened 2020-08-17 23:44 UTC
When I want to post a message, I get this error:
Notice: Undefined variable: postParentObject in file /modules/newbb/include/form.post.php line 66

This error only appears when responding to a post (reply button) and using DHTML and TinyMCE editor, not the plain text.

___

My config:

PHP 7.4.7
MYSQL 5.7.30-0ubuntu0.16.04.1
XOOPS 2.5.11-Beta1

**Comment by cesagonchu** [comment] 2020-10-23 19:51
UP!

**Comment by zyspec** [comment] 2020-10-26 18:04
@cesagonchu 

You should be able to eliminate the error by changing line 66 from
```php
if (null === $postParentObject) {
```
to
```php
if (!$postParentObject instanceof New\Post) {
```
This should remove the problem you're seeing - although it's not 'foolproof'...

**Comment by cesagonchu** [comment] 2020-10-26 19:02
Thanks i will try!

**Comment by cesagonchu** [comment] 2020-10-26 20:10
With your modification i get this error now:

`Error: ParseError: syntax error, unexpected 'New' (T_NEW) in file /modules/newbb/include/form.post.php line 66`

**Comment by mambax7** [comment] 2020-10-26 21:11
Please change the line to:

```php
    if (empty($postParentObject)) {
```

and let me know if it works.

BTW - was it happening when the Admin was posting, or just the Registered user?

**Comment by mambax7** [comment] 2020-10-26 21:16
You might also try Zyspec's approach, but with 
```php
if (!$postParentObject instanceof Newbb\Post) {
```

I think, he missed the "bb" in New\Post

**Comment by cesagonchu** [comment] 2020-10-26 21:24
Yes i posted it as admin.
I will try both solutions, thanks!

**Comment by cesagonchu** [comment] 2020-10-26 21:36
You solution:
if (empty($postParentObject)) {
fixed the issue.

Zyspec's solution (if (!$postParentObject instanceof Newbb\Post) { ) still give this error:
Notice: Undefined variable: postParentObject in file /modules/newbb/include/form.post.php line 66

**Comment by zyspec** [comment] 2020-10-27 19:17
> With your modification i get this error now:
> 
> `Error: ParseError: syntax error, unexpected 'New' (T_NEW) in file /modules/newbb/include/form.post.php line 66`
> 
> My config:
> 
> PHP 7.4.9
> MYSQL 5.7.31-0ubuntu0.16.04.1
> XOOPS 2.5.11-Beta1

Mamba's correct should have been `Newbb\Post`, not `New\Post` - sorry about that.

**Comment by mambax7** [comment] 2021-08-10 00:22
Is this still an issue? I couldn't reproduce it here...

**Comment by cesagonchu** [comment] 2021-08-10 03:01
I think it's ok because as I had specified, `if (empty($postParentObject)) {` fixed the issue.
I will do some tests today and I will close this issue if it's ok.

**Comment by cesagonchu** [comment] 2021-08-10 07:09
I still get this error:
`Notice: Undefined variable: postParentObject in file /modules/newbb/include/form.post.php line 85`

To reproduce it, go on user side and try to post a messageon the forum. Only select "TinyMCE" as editor and dont click to the button "post". Just look at the bottom of the page and you'll see the error.

**Comment by cesagonchu** [comment] 2021-08-10 07:17
Ok I know why I still get this error.
You did'nt change the lines in file /modules/newbb/include/form.post.php line 85:

`if (null === $postParentObject) {`
with
`if (!$postParentObject instanceof Newbb\Post) {`

**Comment by mambax7** [comment] 2021-08-10 07:27
Fixed in: https://github.com/XoopsModules25x/newbb/pull/127/commits/342e4ce47f361eb0b8887be8d636e2dac0479bbc

**Closed by mambax7** 2021-08-10 07:27 UTC
